# Generated by Django 5.2 on 2025-09-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('workspace', 'Workspace'), ('public', 'Public')], default='private', max_length=20),
        ),
    ]
