# Generated by Django 5.2 on 2025-10-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_alter_board_created_by_alter_board_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='board_creation_policy',
            field=models.CharField(choices=[('members', 'Members can create boards'), ('admins', 'Only workspace admins'), ('owner', 'Only workspace owner')], default='members', max_length=16),
        ),
    ]
