# Generated by Django 5.2 on 2025-10-06 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_workspace_board_creation_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='owned_by',
            field=models.ForeignKey(blank=True, help_text='Current owner (can be transferred)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
