# Generated by Django 5.2 on 2025-10-12 09:20

import boards.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(default='attachments/placeholder.txt', upload_to=boards.models.Attachment.safe_upload_to),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['list', 'position'], name='boards_card_list_id_1ea5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['due_date'], name='boards_card_due_dat_64f410_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['created_by', 'list'], name='boards_card_created_9aaa3f_idx'),
        ),
    ]
