# Generated by Django 5.2 on 2025-10-12 13:52

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_alter_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=boards.models.Attachment.safe_upload_to),
        ),
    ]
