# Generated by Django 5.2 on 2025-10-12 09:20

import auth_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail version (40x40) for cards/members', null=True, upload_to=auth_app.models.avatar_upload_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_discoverable',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['display_name'], name='user_profil_display_fc0881_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_discoverable'], name='user_profil_is_disc_c1aad7_idx'),
        ),
    ]
